### ISSUE TITLE
Automatron: Self Healing Infrastructure

### ISSUE THREAD

**Issue by madflojo** [thechangelog/ping#636]
[Automatron](https://github.com/madflojo/automatron) is a framework for creating self healing infrastructure. Basically, its a simple lightweight monitoring system that allows you to define actions when health checks return a specified status.

Here are a few features from the README.

## Features

* Automatically detect and add new systems to monitor
* Monitoring is executed over SSH and completely agent-less
* Policy based Runbooks allow for monitoring policies rather than server specific configurations
* Supports Nagios compliant health check scripts
* Allows arbitrary shell commands for both checks and actions
* Runbook flexibility with **Jinja2** templating support
* Pluggable Architecture that simplifies customization

## Example Runbook

Runbooks are both the monitoring and action definitions for Automatron. Essentially in this you will define a check (or multiple checks) and actions.

```yaml+jinja
name: Verify HTTP is responding to GET requests on target system
schedule: "*/2 * * * *"
nodes:
  - "*"
checks:
  http_is_accessible:
    execute_from: remote
    type: cmd
    cmd: /usr/bin/curl -Lw "Response %{http_code}\\n" http://{{ facts['network']['eth0']['v4'][0] }} -o /dev/null | egrep "Response [200|301]"
actions:
  restart_http:
    execute_from: ontarget
    trigger: 0
    frequency: 0
    call_on:
      - WARNING
      - CRITICAL
      - UNKNOWN
    type: cmd
    cmd: service nginx restart
  remove_dns:
    execute_from: remote
    trigger: 0
    frequency: 300
    call_on:
      - WARNING
      - CRITICAL
      - UNKNOWN
    type: plugin
    plugin: cloudflare/dns.py
    args: remove ben@example.com api-key example.com --content {{ facts['network']['eth0']['v4'][0] }}
  reboot_db:
    execute_from: local
    trigger: 10
    frequency: 900
    call_on:
      - WARNING
      - CRITICAL
      - UNKNOWN
    type: cmd
    cmd: ssh mysql.example.com "reboot"
```
